// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $about_index from "./routes/about/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $links_middleware from "./routes/links/_middleware.ts";
import * as $links_index from "./routes/links/index.tsx";
import * as $posts_slug_ from "./routes/posts/[slug].tsx";
import * as $posts_middleware from "./routes/posts/_middleware.ts";
import * as $posts_index from "./routes/posts/index.tsx";
import * as $works_index from "./routes/works/index.tsx";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/about/index.tsx": $about_index,
    "./routes/index.tsx": $index,
    "./routes/links/_middleware.ts": $links_middleware,
    "./routes/links/index.tsx": $links_index,
    "./routes/posts/[slug].tsx": $posts_slug_,
    "./routes/posts/_middleware.ts": $posts_middleware,
    "./routes/posts/index.tsx": $posts_index,
    "./routes/works/index.tsx": $works_index,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
